<?xml version="1.0" encoding="utf-8"?>
<!--
  Pretty Feed — Atom feed stylesheet
  Adapted from aboutfeeds.com pretty-feed-v3 for Atom namespace.
  Makes raw XML feeds readable in browsers.
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns="http://www.w3.org/2005/Atom">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <title><xsl:value-of select="feed/title"/> — Feed</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <style>
          * { margin:0; padding:0; box-sizing:border-box; }
          body {
            font-family: -apple-system, 'Segoe UI', Roboto, 'Noto Sans SC', sans-serif;
            background:#f5f5f5; color:#333; line-height:1.6;
          }
          .container { max-width:720px; margin:0 auto; padding:24px 16px; }
          header {
            background:#fff; border-radius:12px; padding:24px 20px;
            margin-bottom:20px; box-shadow:0 1px 3px rgba(0,0,0,.08);
          }
          header h1 { font-size:22px; font-weight:700; color:#1a1a2e; margin-bottom:6px; }
          header p { font-size:14px; color:#666; }
          header .meta {
            margin-top:12px; padding-top:12px; border-top:1px solid #eee;
            font-size:12px; color:#999; display:flex; gap:16px; flex-wrap:wrap;
          }
          header .meta a { color:#217346; text-decoration:none; }
          header .meta a:hover { text-decoration:underline; }

          .notice {
            background:#e8f5e9; border:1px solid #c8e6c9; border-radius:8px;
            padding:12px 16px; margin-bottom:20px; font-size:13px; color:#2e7d32;
          }
          .notice a { color:#1565c0; font-weight:500; }

          article {
            background:#fff; border-radius:12px; padding:20px;
            margin-bottom:16px; box-shadow:0 1px 3px rgba(0,0,0,.08);
            transition:box-shadow .2s;
          }
          article:hover { box-shadow:0 4px 12px rgba(0,0,0,.12); }
          article h2 { font-size:17px; font-weight:600; margin-bottom:8px; }
          article h2 a { color:#1a1a2e; text-decoration:none; }
          article h2 a:hover { color:#217346; }
          article .time { font-size:12px; color:#999; margin-bottom:8px; }
          article .desc { font-size:14px; color:#555; line-height:1.7; }
          article .desc a { color:#217346; }

          footer {
            text-align:center; padding:24px; font-size:12px; color:#aaa;
          }
          footer a { color:#217346; }
        </style>
      </head>
      <body>
        <div class="container">
          <header>
            <h1><xsl:value-of select="feed/title"/></h1>
            <p><xsl:value-of select="feed/subtitle"/></p>
            <div class="meta">
              <span>
                <xsl:variable name="selfLink" select="feed/link[@rel='self']/@href"/>
                <xsl:if test="$selfLink">
                  <a href="{$selfLink}">Atom Feed</a>
                </xsl:if>
              </span>
              <span>
                <xsl:variable name="siteLink" select="feed/link[@rel='alternate']/@href"/>
                <xsl:if test="$siteLink">
                  <a href="{$siteLink}">Website</a>
                </xsl:if>
              </span>
              <span><xsl:value-of select="count(feed/entry)"/> entries</span>
            </div>
          </header>

          <div class="notice">
            This is an <strong>RSS/Atom feed</strong>. Copy the URL into your
            <a href="https://aboutfeeds.com/" target="_blank">feed reader</a> to subscribe.
          </div>

          <xsl:for-each select="feed/entry">
            <article>
              <h2>
                <a href="{link[@rel='alternate']/@href}" target="_blank">
                  <xsl:value-of select="title"/>
                </a>
              </h2>
              <div class="time">
                <xsl:value-of select="updated"/>
              </div>
              <div class="desc">
                <xsl:choose>
                  <xsl:when test="summary">
                    <xsl:value-of select="summary" disable-output-escaping="yes"/>
                  </xsl:when>
                  <xsl:when test="content">
                    <xsl:value-of select="content" disable-output-escaping="yes"/>
                  </xsl:when>
                </xsl:choose>
              </div>
            </article>
          </xsl:for-each>

          <footer>
            Generated by <a href="https://github.com/gitfox-enter/RSSForge" target="_blank">RSSForge</a>
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
